name: Parse and upload provenance data 

on:
  workflow_call:
    inputs:
      repo-path:
        description: "Relative path to caller repo checkout"
        required: false
        type: string
        default: "."
    secrets:
      GRAPHDB_URL:
        required: true
      GRAPHDB_REPOSITORY:
        required: true
      GRAPHDB_USERNAME:
        required: true
      GRAPHDB_PASSWORD:
        required: true

jobs:
  run-shared-script:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout caller repository
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: caller-repo

      # 2. Checkout shared repository (this repo)
      - name: Checkout shared repository
        uses: actions/checkout@v4
        with:
          repository: e-laute/E-LAUTE_GH_Actions
          ref: main
          path: shared-actions

      # 3. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 4. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r shared-actions/scripts/requirements.txt

      # 5. Run the shared script *on the caller repo*
      - name: Run shared Python script
        run: |
          export GRAPHDB_URL="${{ secrets.GRAPHDB_URL}}"
          export GRAPHDB_REPOSITORY="${{ secrets.GRAPHDB_REPOSITORY}}"
          export GRAPHDB_USERNAME="${{ secrets.GRAPHDB_USERNAME}}"
          export GRAPHDB_PASSWORD="${{ secrets.GRAPHDB_PASSWORD}}"
          export INPUT_PATH="${{ github.workspace }}/caller-repo"
          python shared-actions/scripts/upload_to_graphdb.py
